name: tali
adopt-info: tali
summary: Roll dice and score points
description: |
  A variation on poker with dice and less money, this game is a family classic.
  Throw the dice three times in a row, holding back the ones you like, in order
  to make the best possible hand. You can also play a lesser-known variant with
  colored dice.

  Play between one and five opponents at three difficulty levels.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  tali:
    interface: dbus
    bus: session
    name: org.gnome.Tali

layout:
 /usr/share/tali:
   symlink: $SNAP/usr/share/tali

apps:
  tali:
    command: usr/bin/tali
    extensions: [gnome]
    desktop: usr/share/applications/org.gnome.Tali.desktop

parts:
  tali:
    source: https://gitlab.gnome.org/GNOME/tali.git
    source-type: git
    source-tag: '40.7'
    parse-info: [usr/share/metainfo/org.gnome.Tali.appdata.xml]
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Tali$|=${SNAP}/meta/gui/org.gnome.Tali.svg|g' $CRAFT_PART_SRC/data/org.gnome.Tali.desktop.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/scalable/org.gnome.Tali.svg $CRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
      - --prefix=/usr
